telegram_token: "8194751068:AAHIXjZXfXI6CDI3i6bZYtTu_p091a9vUK4"
openai_api_key: "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"
